In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df_train=pd.read_csv('../../data/F1/train.csv')
df_test=pd.read_csv('../../data/F1/test.csv')
print(df_train.shape)
df_train.head()

(439140, 16)

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [8]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439140 entries, 0 to 439139
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      439140 non-null  int64
 1   Driver                  439140 non-null  object
 2   Compound                439140 non-null  object
 3   Race                    439140 non-null  object
 4   Year                    439140 non-null  int64
 5   PitStop                 439140 non-null  int64
 6   LapNumber               439140 non-null  int64
 7   Stint                   439140 non-null  int64
 8   TyreLife                439140 non-null  float64
 9   Position                439140 non-null  int64
 10  LapTime (s)             439140 non-null  float64
 11  LapTime_Delta           439140 non-null  float64
 12  Cumulative_Degradation  439140 non-null  float64
 13  RaceProgress            439140 non-null  float64
 14  Position_Change         439140 non-null  float64
 15  PitNextLap              439140 non-null  float64
dtypes: float64(7), int64(6), object(3)
memory usage: 53.6+ MB

In [9]:
df_train.describe()

,id,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
count,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000,439140.000000
mean,219569.500000,2023.523544,0.136118,23.105909,1.789113,14.158231,9.630339,90.948735,-3.770040,-25.721759,0.337661,0.101542,0.198982
std,126768.942943,1.024930,0.342915,16.958261,0.950194,9.801338,5.278770,19.772769,43.945759,54.766573,0.253277,4.006765,0.399235
min,0.000000,2022.000000,0.000000,1.000000,1.000000,1.000000,1.000000,67.694000,-2403.895000,-274.564000,0.012821,-18.000000,0.000000
25%,109784.750000,2023.000000,0.000000,9.000000,1.000000,6.000000,5.000000,82.621000,-8.884000,-46.566250,0.129870,-1.000000,0.000000
50%,219569.500000,2024.000000,0.000000,19.000000,2.000000,12.000000,10.000000,90.521000,-0.295000,-20.994000,0.269231,0.000000,0.000000
75%,329354.250000,2024.000000,0.000000,36.000000,2.000000,20.000000,14.000000,98.471000,0.115000,-6.199000,0.513158,2.000000,0.000000
max,439139.000000,2025.000000,1.000000,78.000000,8.000000,77.000000,20.000000,2507.607000,2423.932000,2412.026000,1.000000,18.000000,1.000000

## Data cleaning

In [10]:
drop_cols=['id']
df_train_clean=df_train.drop(drop_cols,axis=1)
df_test_clean=df_test.drop(drop_cols,axis=1)

## Prepocessing

In [15]:
n_train=df_train_clean.shape[0]
all_features=pd.concat([df_train_clean.drop(columns='PitNextLap'),df_test_clean],axis=0)
all_features.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change
0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0
1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0
2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0
3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0
4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0

In [18]:
#one-hot
df_onehot=pd.get_dummies(all_features,dtype=bool)
df_onehot.head()

,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,...,Race_Mexico City Grand Prix,Race_Miami Grand Prix,Race_Monaco Grand Prix,Race_Pre-Season Testing,Race_Qatar Grand Prix,Race_Saudi Arabian Grand Prix,Race_Singapore Grand Prix,Race_Spanish Grand Prix,Race_São Paulo Grand Prix,Race_United States Grand Prix
0,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,...,False,False,False,False,False,False,False,False,False,False
1,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,...,False,False,False,False,False,False,False,False,False,False
2,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,...,False,False,False,False,False,False,False,False,False,False
3,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,...,False,False,False,True,False,False,False,False,False,False
4,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,...,False,False,False,False,False,False,False,False,False,False

In [38]:
numeric_features=df_onehot.select_dtypes(exclude=bool).columns
cat_features=df_onehot.select_dtypes(include=bool).columns
X_train_onehot=df_onehot.iloc[:n_train,:]
X_test_onehot=df_onehot.iloc[n_train:,:]
X_train_onehot.head()

,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,...,Race_Mexico City Grand Prix,Race_Miami Grand Prix,Race_Monaco Grand Prix,Race_Pre-Season Testing,Race_Qatar Grand Prix,Race_Saudi Arabian Grand Prix,Race_Singapore Grand Prix,Race_Spanish Grand Prix,Race_São Paulo Grand Prix,Race_United States Grand Prix
0,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,...,False,False,False,False,False,False,False,False,False,False
1,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,...,False,False,False,False,False,False,False,False,False,False
2,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,...,False,False,False,False,False,False,False,False,False,False
3,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,...,False,False,False,True,False,False,False,False,False,False
4,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
stnd=StandardScaler().set_output(transform="pandas")
X_train_scaled=stnd.fit_transform(X_train_onehot[numeric_features])
X_train=pd.concat([X_train_scaled,X_train_onehot[cat_features].astype(float)],axis=1)

X_test_scaled=stnd.transform(X_test_onehot[numeric_features])
X_test=pd.concat([X_test_scaled,X_test_onehot[cat_features].astype(float)],axis=1)

y_train=df_train_clean['PitNextLap']

,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,...,Race_Mexico City Grand Prix,Race_Miami Grand Prix,Race_Monaco Grand Prix,Race_Pre-Season Testing,Race_Qatar Grand Prix,Race_Saudi Arabian Grand Prix,Race_Singapore Grand Prix,Race_Spanish Grand Prix,Race_São Paulo Grand Prix,Race_United States Grand Prix
count,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000,...,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000,188165.000000
mean,0.004778,0.000423,-0.003286,-0.005131,0.000244,-0.004888,0.001929,0.004374,-0.002332,-0.003813,...,0.054718,0.043324,0.048750,0.051269,0.031510,0.041740,0.042968,0.046310,0.027173,0.040821
std,1.000437,1.000451,1.002598,0.998534,1.005249,0.998992,1.054747,0.918143,1.002808,1.000468,...,0.227429,0.203585,0.215345,0.220546,0.174691,0.199995,0.202785,0.210157,0.162588,0.197875
min,-1.486487,-0.396946,-1.303550,-0.830476,-1.342495,-1.634917,-1.210339,-54.600233,-4.543694,-1.282547,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-0.510810,-0.396946,-0.831803,-0.830476,-0.832360,-0.877163,-0.420515,-0.116142,-0.385130,-0.826981,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.464868,-0.396946,-0.242119,0.221941,-0.220198,0.070028,-0.023453,0.079303,0.085723,-0.270177,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.464868,-0.396946,0.760344,0.221941,0.596018,0.827781,0.381144,0.088565,0.356673,0.691574,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.440545,2.519236,3.178047,6.536448,6.411557,1.964411,121.731004,55.460296,44.416227,2.615077,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [48]:
X_train.head()

,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,...,Race_Mexico City Grand Prix,Race_Miami Grand Prix,Race_Monaco Grand Prix,Race_Pre-Season Testing,Race_Qatar Grand Prix,Race_Saudi Arabian Grand Prix,Race_Singapore Grand Prix,Race_Spanish Grand Prix,Race_São Paulo Grand Prix,Race_United States Grand Prix
0,-1.486487,-0.396946,1.585901,0.221941,2.534531,-0.308849,-0.630046,-0.086333,0.853455,1.487008,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.440545,2.519236,0.229628,0.221941,-0.730333,-1.066602,-0.801797,-0.656423,-3.605949,0.033534,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-1.486487,-0.396946,2.116616,1.274359,0.800072,0.638343,-1.011682,-0.085787,-1.365930,1.902200,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-0.510810,-0.396946,-1.244581,-0.830476,-1.240468,-0.498287,0.172574,-0.080872,0.335931,-1.029455,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-1.486487,2.519236,0.170660,1.274359,-0.832360,-1.445478,0.856192,0.289790,0.211493,0.092589,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0